### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by MathieuAbbink** [benkuper/EOS-OSC-Chataigne-Module#1]
Hi Benkuper,

really wanting to use the module. Just curious if you have like a small manual or maybe a list of osc commands that i can use? Is it the same as the osc control from jmcker on Github : https://github.com/jmcker/OSC-Control---ETC-Eos/blob/master/reference/Eos%20OSC%20Keys.pdf

Looking forward hearing from you.
Thanks in advance!

**Comment by benkuper** [comment]
hello, please check on Chataigne's Discord, this module was made a long time ago and I never used it because I don't use this kind of hardware. But you'll find people in the community to help you
